apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregation
  template:
    metadata:
      labels:
        app: aggregation
    spec:
      containers:
      - name: aggregation
        image: hzzanalysis:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
        command: ["python"]
        args: ["/app/aggregation.py"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}
