apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-acquisition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-acquisition
  template:
    metadata:
      labels:
        app: data-acquisition
    spec:
      containers:
      - name: data-acquisition
        image: hzzanalysis:latest
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["/app/data_acquisition.py"]
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq-service
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: data-pvc
